language: generic
#Tell travi ci we need docker ready to go
sudo: require
services:
  - docker

before_install:
  - docker build -t ctso2/docker-react -f Dockerfile.dev .

script: #make sure test suite runs and exits (so it doesnt hang waiting for input)
  - docker run -e CI=true ctso2/docker-react npm run test
